name: jbeltdoctorsrv
version: '3.8'

services:
  nuxt_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jbelt-doctor-web:1.0.0 # Nome immagine leggermente diverso per chiarezza
    container_name: web # Nome container leggermente diverso
    working_dir: /usr/src/app

    volumes:
      # Volume nominato per node_modules. Può ancora essere utile per velocizzare
      # le build successive se le dipendenze non cambiano spesso, mantenendo
      # la cache dei moduli tra una build e l'altra.
      - node_modules_volume:/usr/src/app/node_modules
      - nuxt-app:/usr/src/app/app
    ports:
      - "3000:3000"

    environment:
      - HOST=0.0.0.0
      # Nota: Anche se non c'è live reload, potresti voler eseguire
      # il server di sviluppo per testare il build specifico.
      # Se fosse per produzione, imposteresti NODE_ENV=production
      # e cambieresti il Dockerfile/CMD per lanciare il server buildato.
      - NODE_ENV=development
      # - PORT=3000

    networks:
      - jbelt-network

    restart: unless-stopped
    # Il comando di default del Dockerfile (CMD) verrà usato,
    # avviando 'npx nuxi dev' con il codice presente nell'immagine.

volumes:
  # Volume per node_modules (il nome può rimanere o cambiarlo)
  node_modules_volume:
    name: nuxt4-node-modules
  nuxt-app:
    name: nuxt4-app

networks:
  # La rete esterna come prima
  jbelt-network:
    external: true