# docker-compose.yml - Configurazione principale per deployment Docker
# --------------------------------------------------------------

version: '3.8'

services:
  # Servizio applicazione frontend Nuxt
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jbelt-doctor-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Configurazioni di base
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      
      # Configurazioni API dal nuxt.config.ts
      - NUXT_PUBLIC_API_BASE=http://api:8080
      - NUXT_PUBLIC_API_HOST=api
      - NUXT_PUBLIC_API_PORT=8080
      - NUXT_PUBLIC_FRONTEND_HOST=${FRONTEND_HOST:-localhost}
      - NUXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT:-3000}
    networks:
      - nuxt-network

  # Servizio Nginx come reverse proxy (opzionale ma consigliato)
  nginx:
    image: nginx:stable-alpine
    container_name: nuxt-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - nuxt-app
    networks:
      - nuxt-network

# Definizione della rete Docker
networks:
  nuxt-network:
    driver: bridge

# Version: 1.0.0