# Docker Compose per sviluppo - Frontend JBelt Doctor Web
# Frontend solo con hot reload
# API: atlante.local:8080 (backend esterno)

name: jbelt-frontend-dev

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: jbelt-frontend-dev
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=http://192.168.1.3:8080
      - NUXT_PUBLIC_API_HOST=192.168.1.3
      - NUXT_PUBLIC_API_PORT=8080
      - NUXT_PUBLIC_FRONTEND_HOST=localhost
      - NUXT_PUBLIC_FRONTEND_PORT=3000
      - NUXT_DEBUG=true
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - jbelt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  jbelt-network:
    external: true
    name: jbelt-network