name: jbelt-doctor-web
version: '3.8'

services:
  # Frontend Nuxt.js application (standalone)
  jbelt-doctor-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: jbelt-doctor-web:${JBELT_APP_VERSION:-1.0.0}
    container_name: jbelt-doctor-web
    
    ports:
      - "3000:3000"

    environment:
      - HOST=0.0.0.0
      - NODE_ENV=${NODE_ENV:-development}
      # API configuration for external backend
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE:-http://atlante.local:8080}
      - NUXT_PUBLIC_API_HOST=${NUXT_PUBLIC_API_HOST:-atlante.local}
      - NUXT_PUBLIC_API_PORT=${NUXT_PUBLIC_API_PORT:-8080}
      - NUXT_PUBLIC_FRONTEND_HOST=${NUXT_PUBLIC_FRONTEND_HOST:-localhost}
      - NUXT_PUBLIC_FRONTEND_PORT=${NUXT_PUBLIC_FRONTEND_PORT:-3000}
      - NUXT_DEBUG=${NUXT_DEBUG:-false}

    networks:
      - jbelt-network

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  # Volume per node_modules (il nome può rimanere o cambiarlo)
  node_modules_volume:
    name: nuxt4-node-modules
  nuxt-app:
    name: nuxt4-app

networks:
  # La rete esterna come prima
  jbelt-network:
    external: true