# Docker Compose per produzione Ubuntu con Plesk
# Frontend: jbelt.org:80, API: jbelt.org:8080
# Compatibile con backend docker-compose-srv.yml esistente

version: '3.8'

name: jbelt-ubuntu-prod

services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: jbelt-frontend-ubuntu
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
      - NUXT_PUBLIC_API_HOST=${NUXT_PUBLIC_API_HOST}
      - NUXT_PUBLIC_API_PORT=${NUXT_PUBLIC_API_PORT}
      - NUXT_PUBLIC_FRONTEND_HOST=${NUXT_PUBLIC_FRONTEND_HOST}
      - NUXT_PUBLIC_FRONTEND_PORT=${NUXT_PUBLIC_FRONTEND_PORT}
      - NUXT_DEBUG=${NUXT_DEBUG}
      - NODE_OPTIONS=${NODE_OPTIONS}
      - SSL_ENABLED=${SSL_ENABLED}
    networks:
      - jbelt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx-ubuntu:
    image: nginx:alpine
    container_name: jbelt-nginx-ubuntu
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ubuntu.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend-prod
    networks:
      - jbelt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  jbelt-network:
    external: true
    name: jbelt-network